export let fakeEventBriteEvents =[
    {
        "name": {
            "text": "Tamiola's Event",
            "html": "Tamiola&#39;s Event"
        },
        "description": {
            "text": null,
            "html": null
        },
        "url": "https://www.eventbrite.com/e/tamiolas-event-tickets-509381924047",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-01-09T06:00:00",
            "utc": "2023-01-09T11:00:00Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-01-10T06:01:00",
            "utc": "2023-01-10T11:01:00Z"
        },
        "organization_id": "1322280652203",
        "created": "2023-01-07T16:02:02Z",
        "changed": "2023-01-07T16:02:02Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": null,
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "509381924047",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/509381924047/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Sheena's Awesome Event",
            "html": "Sheena&#39;s Awesome Event"
        },
        "description": {
            "text": "Sheen is the best PM ever!!!!",
            "html": "Sheen is the best PM ever!!!!"
        },
        "url": "https://www.eventbrite.com/e/sheenas-awesome-event-tickets-492783186777",
        "start": {
            "timezone": "UTC",
            "local": "2023-01-18T01:11:00",
            "utc": "2023-01-18T01:11:00Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-01-20T03:46:34",
            "utc": "2023-01-20T03:46:34Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:41:39Z",
        "changed": "2023-01-07T21:13:40Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Sheen is the best PM ever!!!!",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492783186777",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492783186777/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Jay event",
            "html": "Jay event"
        },
        "description": {
            "text": null,
            "html": null
        },
        "url": "https://www.eventbrite.com/e/jay-event-tickets-509371302277",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-01-20T05:39:00",
            "utc": "2023-01-20T10:39:00Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-01-21T05:40:00",
            "utc": "2023-01-21T10:40:00Z"
        },
        "organization_id": "1322280652203",
        "created": "2023-01-07T15:41:05Z",
        "changed": "2023-01-07T15:41:05Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": null,
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "509371302277",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/509371302277/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "asdadasd",
            "html": "asdadasd"
        },
        "description": {
            "text": null,
            "html": null
        },
        "url": "https://www.eventbrite.com/e/asdadasd-tickets-509374572057",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-01-21T05:51:00",
            "utc": "2023-01-21T10:51:00Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-01-22T05:51:00",
            "utc": "2023-01-22T10:51:00Z"
        },
        "organization_id": "1322280652203",
        "created": "2023-01-07T15:52:13Z",
        "changed": "2023-01-07T15:52:13Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": null,
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "509374572057",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/509374572057/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "PoV Test Russ",
            "html": "PoV Test Russ"
        },
        "description": {
            "text": "My amazing description",
            "html": "My amazing description"
        },
        "url": "https://www.eventbrite.com/e/pov-test-russ-tickets-515121832267",
        "start": {
            "timezone": "UTC",
            "local": "2023-01-21T07:55:00",
            "utc": "2023-01-21T07:55:00Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-01-21T07:55:00",
            "utc": "2023-01-21T07:55:00Z"
        },
        "organization_id": "1322280652203",
        "created": "2023-01-13T18:56:59Z",
        "changed": "2023-01-14T16:08:07Z",
        "published": "2023-01-13T18:57:01Z",
        "capacity": 100000,
        "capacity_is_custom": false,
        "status": "live",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "My amazing description",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "515121832267",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/515121832267/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": [
            {
                "actual_cost": null,
                "actual_fee": null,
                "cost": null,
                "fee": null,
                "tax": null,
                "resource_uri": "https://www.eventbriteapi.com/v3/events/515121832267/ticket_classes/865015609/",
                "display_name": "general",
                "name": "general",
                "description": null,
                "sorting": 1,
                "donation": false,
                "free": true,
                "minimum_quantity": 1,
                "maximum_quantity": null,
                "maximum_quantity_per_order": 10,
                "on_sale_status": "AVAILABLE",
                "has_pdf_ticket": true,
                "order_confirmation_message": null,
                "delivery_methods": [
                    "electronic"
                ],
                "category": "admission",
                "sales_channels": [
                    "online",
                    "atd"
                ],
                "secondary_assignment_enabled": false,
                "event_id": "515121832267",
                "image_id": null,
                "id": "865015609",
                "capacity": 100000,
                "quantity_total": 100000,
                "quantity_sold": 0,
                "sales_start": "2023-01-13T13:57:00Z",
                "sales_end": "2023-01-21T06:55:00Z",
                "sales_end_relative": null,
                "hidden": false,
                "hidden_currently": false,
                "include_fee": false,
                "split_fee": false,
                "hide_description": true,
                "hide_sale_dates": false,
                "auto_hide": false,
                "payment_constraints": []
            }
        ]
    },
    {
        "name": {
            "text": "Cham's Suprising Event",
            "html": "Cham&#39;s Suprising Event"
        },
        "description": {
            "text": "My amazing event description",
            "html": "My amazing event description"
        },
        "url": "https://www.eventbrite.com/e/chams-suprising-event-tickets-515810321557",
        "start": {
            "timezone": "UTC",
            "local": "2023-01-21T12:28:00",
            "utc": "2023-01-21T12:28:00Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-01-24T12:28:00",
            "utc": "2023-01-24T12:28:00Z"
        },
        "organization_id": "1322280652203",
        "created": "2023-01-14T22:30:13Z",
        "changed": "2023-01-14T23:24:09Z",
        "published": "2023-01-14T22:30:15Z",
        "capacity": 400000,
        "capacity_is_custom": false,
        "status": "live",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": false,
        "version": null,
        "summary": "My amazing event description",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "515810321557",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/515810321557/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": [
            {
                "actual_cost": null,
                "actual_fee": null,
                "cost": null,
                "fee": null,
                "tax": null,
                "resource_uri": "https://www.eventbriteapi.com/v3/events/515810321557/ticket_classes/866236699/",
                "display_name": "general",
                "name": "general",
                "description": null,
                "sorting": 1,
                "donation": false,
                "free": true,
                "minimum_quantity": 1,
                "maximum_quantity": null,
                "maximum_quantity_per_order": 10,
                "on_sale_status": "AVAILABLE",
                "has_pdf_ticket": true,
                "order_confirmation_message": null,
                "delivery_methods": [
                    "electronic"
                ],
                "category": "admission",
                "sales_channels": [
                    "online",
                    "atd"
                ],
                "secondary_assignment_enabled": false,
                "event_id": "515810321557",
                "image_id": null,
                "id": "866236699",
                "capacity": 100000,
                "quantity_total": 100000,
                "quantity_sold": 0,
                "sales_start": "2023-01-14T17:30:14Z",
                "sales_end": "2023-01-20T23:28:00Z",
                "sales_end_relative": null,
                "hidden": false,
                "hidden_currently": false,
                "include_fee": false,
                "split_fee": false,
                "hide_description": true,
                "hide_sale_dates": false,
                "auto_hide": false,
                "payment_constraints": []
            },
            {
                "actual_cost": null,
                "actual_fee": {
                    "display": "$2.51",
                    "currency": "USD",
                    "value": 251,
                    "major_value": "2.51"
                },
                "cost": {
                    "display": "$10.00",
                    "currency": "USD",
                    "value": 1000,
                    "major_value": "10.00"
                },
                "fee": {
                    "display": "$2.51",
                    "currency": "USD",
                    "value": 251,
                    "major_value": "2.51"
                },
                "tax": {
                    "display": "$0.00",
                    "currency": "USD",
                    "value": 0,
                    "major_value": "0.00"
                },
                "resource_uri": "https://www.eventbriteapi.com/v3/events/515810321557/ticket_classes/866237269/",
                "display_name": "general",
                "name": "general",
                "description": null,
                "sorting": 2,
                "donation": false,
                "free": false,
                "minimum_quantity": 1,
                "maximum_quantity": null,
                "maximum_quantity_per_order": 10,
                "on_sale_status": "AVAILABLE",
                "has_pdf_ticket": true,
                "order_confirmation_message": null,
                "delivery_methods": [
                    "electronic"
                ],
                "category": "admission",
                "sales_channels": [
                    "online",
                    "atd"
                ],
                "secondary_assignment_enabled": false,
                "event_id": "515810321557",
                "image_id": null,
                "id": "866237269",
                "capacity": 100000,
                "quantity_total": 100000,
                "quantity_sold": 0,
                "sales_start": "2023-01-14T22:32:05Z",
                "sales_end": "2023-01-21T11:28:00Z",
                "sales_end_relative": null,
                "hidden": false,
                "hidden_currently": false,
                "include_fee": false,
                "split_fee": false,
                "hide_description": true,
                "hide_sale_dates": false,
                "auto_hide": false,
                "payment_constraints": []
            },
            {
                "actual_cost": null,
                "actual_fee": null,
                "cost": null,
                "fee": null,
                "tax": null,
                "resource_uri": "https://www.eventbriteapi.com/v3/events/515810321557/ticket_classes/866251819/",
                "display_name": "general",
                "name": "general",
                "description": null,
                "sorting": 4,
                "donation": false,
                "free": true,
                "minimum_quantity": 1,
                "maximum_quantity": null,
                "maximum_quantity_per_order": 10,
                "on_sale_status": "AVAILABLE",
                "has_pdf_ticket": true,
                "order_confirmation_message": null,
                "delivery_methods": [
                    "electronic"
                ],
                "category": "admission",
                "sales_channels": [
                    "online",
                    "atd"
                ],
                "secondary_assignment_enabled": false,
                "event_id": "515810321557",
                "image_id": null,
                "id": "866251819",
                "capacity": 100000,
                "quantity_total": 100000,
                "quantity_sold": 0,
                "sales_start": "2023-01-14T23:09:42Z",
                "sales_end": "2023-01-21T11:28:00Z",
                "sales_end_relative": null,
                "hidden": false,
                "hidden_currently": false,
                "include_fee": false,
                "split_fee": false,
                "hide_description": true,
                "hide_sale_dates": false,
                "auto_hide": false,
                "payment_constraints": []
            },
            {
                "actual_cost": null,
                "actual_fee": {
                    "display": "$3.11",
                    "currency": "USD",
                    "value": 311,
                    "major_value": "3.11"
                },
                "cost": {
                    "display": "$19.00",
                    "currency": "USD",
                    "value": 1900,
                    "major_value": "19.00"
                },
                "fee": {
                    "display": "$3.11",
                    "currency": "USD",
                    "value": 311,
                    "major_value": "3.11"
                },
                "tax": {
                    "display": "$0.00",
                    "currency": "USD",
                    "value": 0,
                    "major_value": "0.00"
                },
                "resource_uri": "https://www.eventbriteapi.com/v3/events/515810321557/ticket_classes/866255999/",
                "display_name": "general",
                "name": "general",
                "description": null,
                "sorting": 5,
                "donation": false,
                "free": false,
                "minimum_quantity": 1,
                "maximum_quantity": null,
                "maximum_quantity_per_order": 10,
                "on_sale_status": "AVAILABLE",
                "has_pdf_ticket": true,
                "order_confirmation_message": null,
                "delivery_methods": [
                    "electronic"
                ],
                "category": "admission",
                "sales_channels": [
                    "online",
                    "atd"
                ],
                "secondary_assignment_enabled": false,
                "event_id": "515810321557",
                "image_id": null,
                "id": "866255999",
                "capacity": 100000,
                "quantity_total": 100000,
                "quantity_sold": 0,
                "sales_start": "2023-01-14T23:24:10Z",
                "sales_end": "2023-01-21T11:28:00Z",
                "sales_end_relative": null,
                "hidden": false,
                "hidden_currently": false,
                "include_fee": false,
                "split_fee": false,
                "hide_description": true,
                "hide_sale_dates": false,
                "auto_hide": false,
                "payment_constraints": []
            }
        ]
    },
    {
        "name": {
            "text": "Russ's Fantastic Event",
            "html": "Russ&#39;s Fantastic Event"
        },
        "description": {
            "text": "Id dolorum cum aut voluptate maxime laborum adipisci culpa. Amet accusantium totam soluta atque quas.",
            "html": "Id dolorum cum aut voluptate maxime laborum adipisci culpa. Amet accusantium totam soluta atque quas."
        },
        "url": "https://www.eventbrite.com/e/russs-fantastic-event-tickets-492779074477",
        "start": {
            "timezone": "UTC",
            "local": "2023-01-25T09:00:00",
            "utc": "2023-01-25T09:00:00Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-01-27T10:00:00",
            "utc": "2023-01-27T10:00:00Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:14Z",
        "changed": "2023-01-14T22:12:20Z",
        "capacity": 300000,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": false,
        "version": null,
        "summary": "Id dolorum cum aut voluptate maxime laborum adipisci culpa. Amet accusantium totam soluta atque quas.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492779074477",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492779074477/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": [
            {
                "actual_cost": null,
                "actual_fee": {
                    "display": "$2.51",
                    "currency": "USD",
                    "value": 251,
                    "major_value": "2.51"
                },
                "cost": {
                    "display": "$10.00",
                    "currency": "USD",
                    "value": 1000,
                    "major_value": "10.00"
                },
                "fee": {
                    "display": "$2.51",
                    "currency": "USD",
                    "value": 251,
                    "major_value": "2.51"
                },
                "tax": {
                    "display": "$0.00",
                    "currency": "USD",
                    "value": 0,
                    "major_value": "0.00"
                },
                "resource_uri": "https://www.eventbriteapi.com/v3/events/492779074477/ticket_classes/866225859/",
                "display_name": "general",
                "name": "general",
                "description": null,
                "sorting": 1,
                "donation": false,
                "free": false,
                "minimum_quantity": 1,
                "maximum_quantity": null,
                "maximum_quantity_per_order": 10,
                "on_sale_status": "AVAILABLE",
                "has_pdf_ticket": true,
                "order_confirmation_message": null,
                "delivery_methods": [
                    "electronic"
                ],
                "category": "admission",
                "sales_channels": [
                    "online",
                    "atd"
                ],
                "secondary_assignment_enabled": false,
                "event_id": "492779074477",
                "image_id": null,
                "id": "866225859",
                "capacity": 100000,
                "quantity_total": 100000,
                "quantity_sold": 0,
                "sales_start": "2023-01-14T22:09:39Z",
                "sales_end": "2023-01-25T08:00:00Z",
                "sales_end_relative": null,
                "hidden": false,
                "hidden_currently": false,
                "include_fee": false,
                "split_fee": false,
                "hide_description": true,
                "hide_sale_dates": false,
                "auto_hide": false,
                "payment_constraints": []
            },
            {
                "actual_cost": null,
                "actual_fee": null,
                "cost": null,
                "fee": null,
                "tax": null,
                "resource_uri": "https://www.eventbriteapi.com/v3/events/492779074477/ticket_classes/866226339/",
                "display_name": "general",
                "name": "general",
                "description": null,
                "sorting": 2,
                "donation": false,
                "free": true,
                "minimum_quantity": 1,
                "maximum_quantity": null,
                "maximum_quantity_per_order": 10,
                "on_sale_status": "AVAILABLE",
                "has_pdf_ticket": true,
                "order_confirmation_message": null,
                "delivery_methods": [
                    "electronic"
                ],
                "category": "admission",
                "sales_channels": [
                    "online",
                    "atd"
                ],
                "secondary_assignment_enabled": false,
                "event_id": "492779074477",
                "image_id": null,
                "id": "866226339",
                "capacity": 100000,
                "quantity_total": 100000,
                "quantity_sold": 0,
                "sales_start": "2023-01-14T22:11:19Z",
                "sales_end": "2023-01-25T08:00:00Z",
                "sales_end_relative": null,
                "hidden": false,
                "hidden_currently": false,
                "include_fee": false,
                "split_fee": false,
                "hide_description": true,
                "hide_sale_dates": false,
                "auto_hide": false,
                "payment_constraints": []
            },
            {
                "actual_cost": null,
                "actual_fee": null,
                "cost": null,
                "fee": null,
                "tax": null,
                "resource_uri": "https://www.eventbriteapi.com/v3/events/492779074477/ticket_classes/866226589/",
                "display_name": "general",
                "name": "general",
                "description": null,
                "sorting": 3,
                "donation": false,
                "free": true,
                "minimum_quantity": 1,
                "maximum_quantity": null,
                "maximum_quantity_per_order": 10,
                "on_sale_status": "AVAILABLE",
                "has_pdf_ticket": true,
                "order_confirmation_message": null,
                "delivery_methods": [
                    "electronic"
                ],
                "category": "admission",
                "sales_channels": [
                    "online",
                    "atd"
                ],
                "secondary_assignment_enabled": false,
                "event_id": "492779074477",
                "image_id": null,
                "id": "866226589",
                "capacity": 100000,
                "quantity_total": 100000,
                "quantity_sold": 0,
                "sales_start": "2023-01-14T22:12:21Z",
                "sales_end": "2023-01-25T08:00:00Z",
                "sales_end_relative": null,
                "hidden": false,
                "hidden_currently": false,
                "include_fee": false,
                "split_fee": false,
                "hide_description": true,
                "hide_sale_dates": false,
                "auto_hide": false,
                "payment_constraints": []
            }
        ]
    },
    {
        "name": {
            "text": "POV Sample Event",
            "html": "POV Sample Event"
        },
        "description": {
            "text": null,
            "html": null
        },
        "url": "https://www.eventbrite.com/e/pov-sample-event-tickets-501696135647",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-02-09T19:00:00",
            "utc": "2023-02-10T00:00:00Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-02-09T22:00:00",
            "utc": "2023-02-10T03:00:00Z"
        },
        "organization_id": "1322280652203",
        "created": "2023-01-01T04:42:20Z",
        "changed": "2023-01-01T04:42:20Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": true,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "coyote",
        "is_free": true,
        "version": null,
        "summary": null,
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "501696135647",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/501696135647/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Niema's Memorable Event",
            "html": "Niema&#39;s Memorable Event"
        },
        "description": {
            "text": "Repellendus ipsam commodi libero mollitia. Est odio aspernatur ut voluptates vitae excepturi molestias culpa eveniet.",
            "html": "Repellendus ipsam commodi libero mollitia. Est odio aspernatur ut voluptates vitae excepturi molestias culpa eveniet."
        },
        "url": "https://www.eventbrite.com/e/niemas-memorable-event-tickets-492767971267",
        "start": {
            "timezone": "UTC",
            "local": "2023-02-10T23:20:21",
            "utc": "2023-02-10T23:20:21Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-08-11T05:42:50",
            "utc": "2023-08-11T05:42:50Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:28:57Z",
        "changed": "2023-01-06T23:02:16Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Repellendus ipsam commodi libero mollitia. Est odio aspernatur ut voluptates vitae excepturi molestias culpa eveniet.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492767971267",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492767971267/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Kunte's Event",
            "html": "Kunte&#39;s Event"
        },
        "description": {
            "text": "My events description",
            "html": "My events description"
        },
        "url": "https://www.eventbrite.com/e/kuntes-event-tickets-509386377367",
        "start": {
            "timezone": "UTC",
            "local": "2023-02-15T06:07:00",
            "utc": "2023-02-15T06:07:00Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-02-16T06:07:00",
            "utc": "2023-02-16T06:07:00Z"
        },
        "organization_id": "1322280652203",
        "created": "2023-01-07T16:08:39Z",
        "changed": "2023-01-07T17:37:09Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "My events description",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "509386377367",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/509386377367/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Ant's Exciting Event",
            "html": "Ant&#39;s Exciting Event"
        },
        "description": {
            "text": "Repellendus nam modi. Alias doloribus assumenda esse.",
            "html": "Repellendus nam modi. Alias doloribus assumenda esse."
        },
        "url": "https://www.eventbrite.com/e/ants-exciting-event-tickets-492762354467",
        "start": {
            "timezone": "UTC",
            "local": "2023-03-18T15:38:38",
            "utc": "2023-03-18T15:38:38Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-07-23T12:25:30",
            "utc": "2023-07-23T12:25:30Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:21:56Z",
        "changed": "2023-01-06T14:51:53Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Repellendus nam modi. Alias doloribus assumenda esse.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492762354467",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492762354467/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Katrice's Thrilling Event",
            "html": "Katrice&#39;s Thrilling Event"
        },
        "description": {
            "text": "Optio fugiat quia dignissimos architecto adipisci laborum impedit in. Laudantium cupiditate ullam et blanditiis aperiam.",
            "html": "Optio fugiat quia dignissimos architecto adipisci laborum impedit in. Laudantium cupiditate ullam et blanditiis aperiam."
        },
        "url": "https://www.eventbrite.com/e/katrices-thrilling-event-tickets-492768051507",
        "start": {
            "timezone": "UTC",
            "local": "2023-03-25T16:55:28",
            "utc": "2023-03-25T16:55:28Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-12-30T09:19:39",
            "utc": "2023-12-30T09:19:39Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:29:15Z",
        "changed": "2023-01-06T14:53:10Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Optio fugiat quia dignissimos architecto adipisci laborum impedit in. Laudantium cupiditate ullam et blanditiis aperiam.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492768051507",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492768051507/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "JR's Electrifying Event",
            "html": "JR&#39;s Electrifying Event"
        },
        "description": {
            "text": "Occaecati beatae vel veritatis modi dolorum quae recusandae. Dolorum possimus doloremque aperiam.",
            "html": "Occaecati beatae vel veritatis modi dolorum quae recusandae. Dolorum possimus doloremque aperiam."
        },
        "url": "https://www.eventbrite.com/e/jrs-electrifying-event-tickets-492778482707",
        "start": {
            "timezone": "UTC",
            "local": "2023-04-02T10:31:24",
            "utc": "2023-04-02T10:31:24Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-05-15T18:32:48",
            "utc": "2023-05-15T18:32:48Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:36:43Z",
        "changed": "2023-01-06T14:53:34Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Occaecati beatae vel veritatis modi dolorum quae recusandae. Dolorum possimus doloremque aperiam.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492778482707",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492778482707/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "My Event 36",
            "html": "My Event 36"
        },
        "description": {
            "text": "Laboriosam iure earum suscipit atque consequatur in. Minima saepe id doloremque numquam.",
            "html": "Laboriosam iure earum suscipit atque consequatur in. Minima saepe id doloremque numquam."
        },
        "url": "https://www.eventbrite.com/e/my-event-36-tickets-492781040357",
        "start": {
            "timezone": "UTC",
            "local": "2023-04-11T14:05:56",
            "utc": "2023-04-11T14:05:56Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-07-02T20:25:17",
            "utc": "2023-07-02T20:25:17Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:43Z",
        "changed": "2023-01-05T20:04:05Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Laboriosam iure earum suscipit atque consequatur in. Minima saepe id doloremque numquam.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492781040357",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492781040357/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Ebube's Inspiring Event",
            "html": "Ebube&#39;s Inspiring Event"
        },
        "description": {
            "text": "Id facilis eveniet iure recusandae inventore est tempora. Accusantium modi dolore.",
            "html": "Id facilis eveniet iure recusandae inventore est tempora. Accusantium modi dolore."
        },
        "url": "https://www.eventbrite.com/e/ebubes-inspiring-event-tickets-492783628097",
        "start": {
            "timezone": "UTC",
            "local": "2023-04-14T20:01:14",
            "utc": "2023-04-14T20:01:14Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-05-16T23:27:22",
            "utc": "2023-05-16T23:27:22Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:42:21Z",
        "changed": "2023-01-06T14:54:22Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Id facilis eveniet iure recusandae inventore est tempora. Accusantium modi dolore.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492783628097",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492783628097/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Delectus sapiente laboriosam praesentium nisi vero omnis praesentium. Perspiciatis impedit harum blanditiis repellat nobis.",
            "html": "Delectus sapiente laboriosam praesentium nisi vero omnis praesentium. Perspiciatis impedit harum blanditiis repellat nobis."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492783648157",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-05-20T16:51:49",
            "utc": "2023-05-20T20:51:49Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-09-29T18:17:58",
            "utc": "2023-09-29T22:17:58Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:42:24Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Delectus sapiente laboriosam praesentium nisi vero omnis praesentium. Perspiciatis impedit harum blanditiis repellat nobis.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492783648157",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492783648157/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Event To Be Deleted",
            "html": "Event To Be Deleted"
        },
        "description": {
            "text": "Sunt molestias maxime quos. Quos praesentium voluptate qui quisquam.",
            "html": "Sunt molestias maxime quos. Quos praesentium voluptate qui quisquam."
        },
        "url": "https://www.eventbrite.com/e/event-to-be-deleted-tickets-492781010267",
        "start": {
            "timezone": "UTC",
            "local": "2023-05-27T04:11:15",
            "utc": "2023-05-27T04:11:15Z"
        },
        "end": {
            "timezone": "UTC",
            "local": "2023-08-27T01:03:56",
            "utc": "2023-08-27T01:03:56Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:38Z",
        "changed": "2023-01-07T19:57:27Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": false,
        "shareable": false,
        "invite_only": true,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Sunt molestias maxime quos. Quos praesentium voluptate qui quisquam.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492781010267",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492781010267/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Ratione laudantium consequatur tempora quasi culpa recusandae. Animi quae saepe vitae magni quas vitae unde magnam totam.",
            "html": "Ratione laudantium consequatur tempora quasi culpa recusandae. Animi quae saepe vitae magni quas vitae unde magnam totam."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492765052537",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-05-28T13:28:35",
            "utc": "2023-05-28T17:28:35Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-10-14T18:34:55",
            "utc": "2023-10-14T22:34:55Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:28:26Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Ratione laudantium consequatur tempora quasi culpa recusandae. Animi quae saepe vitae magni quas vitae unde magnam totam.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492765052537",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492765052537/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Incidunt nulla cumque ex at molestias officiis. Quaerat earum voluptatibus asperiores iure.",
            "html": "Incidunt nulla cumque ex at molestias officiis. Quaerat earum voluptatibus asperiores iure."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492778994237",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-05-29T16:54:55",
            "utc": "2023-05-29T20:54:55Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-03-02T01:14:09",
            "utc": "2024-03-02T06:14:09Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:04Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Incidunt nulla cumque ex at molestias officiis. Quaerat earum voluptatibus asperiores iure.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492778994237",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492778994237/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Est debitis ut libero debitis sunt. Dolorem nisi voluptatibus.",
            "html": "Est debitis ut libero debitis sunt. Dolorem nisi voluptatibus."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492768021417",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-06-10T03:14:51",
            "utc": "2023-06-10T07:14:51Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-06-10T03:14:51",
            "utc": "2023-06-10T07:14:51Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:29:06Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Est debitis ut libero debitis sunt. Dolorem nisi voluptatibus.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492768021417",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492768021417/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Deserunt excepturi deleniti temporibus neque ipsa perferendis. Culpa nulla reiciendis officia molestiae molestiae quia.",
            "html": "Deserunt excepturi deleniti temporibus neque ipsa perferendis. Culpa nulla reiciendis officia molestiae molestiae quia."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492779114597",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-06-16T13:33:52",
            "utc": "2023-06-16T17:33:52Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-03-07T02:01:08",
            "utc": "2024-03-07T07:01:08Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:19Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Deserunt excepturi deleniti temporibus neque ipsa perferendis. Culpa nulla reiciendis officia molestiae molestiae quia.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492779114597",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492779114597/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Iure vel a sequi nam earum blanditiis possimus unde. Asperiores minima est nam id omnis veniam laudantium quibusdam.",
            "html": "Iure vel a sequi nam earum blanditiis possimus unde. Asperiores minima est nam id omnis veniam laudantium quibusdam."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492780960117",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-07-02T04:51:50",
            "utc": "2023-07-02T08:51:50Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-03-15T17:40:38",
            "utc": "2024-03-15T21:40:38Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:27Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Iure vel a sequi nam earum blanditiis possimus unde. Asperiores minima est nam id omnis veniam laudantium quibusdam.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492780960117",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492780960117/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Voluptas repellendus sit fugiat ipsa reprehenderit. Libero necessitatibus ratione amet.",
            "html": "Voluptas repellendus sit fugiat ipsa reprehenderit. Libero necessitatibus ratione amet."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492779124627",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-07-02T06:51:19",
            "utc": "2023-07-02T10:51:19Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-06-04T00:26:56",
            "utc": "2024-06-04T04:26:56Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:19Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Voluptas repellendus sit fugiat ipsa reprehenderit. Libero necessitatibus ratione amet.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492779124627",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492779124627/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Animi dolor unde aliquam illo pariatur. Distinctio fuga maxime non soluta itaque deserunt officia neque.",
            "html": "Animi dolor unde aliquam illo pariatur. Distinctio fuga maxime non soluta itaque deserunt officia neque."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492783758487",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-07-02T13:30:00",
            "utc": "2023-07-02T17:30:00Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-05-10T05:57:59",
            "utc": "2024-05-10T09:57:59Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:42:50Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Animi dolor unde aliquam illo pariatur. Distinctio fuga maxime non soluta itaque deserunt officia neque.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492783758487",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492783758487/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Numquam blanditiis qui praesentium mollitia excepturi et. Tempora id ad exercitationem perspiciatis pariatur.",
            "html": "Numquam blanditiis qui praesentium mollitia excepturi et. Tempora id ad exercitationem perspiciatis pariatur."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492782835727",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-08-11T05:51:13",
            "utc": "2023-08-11T09:51:13Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-12-14T05:28:53",
            "utc": "2023-12-14T10:28:53Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:40:39Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Numquam blanditiis qui praesentium mollitia excepturi et. Tempora id ad exercitationem perspiciatis pariatur.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492782835727",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492782835727/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Non illo ratione tenetur eveniet. Animi placeat iure amet.",
            "html": "Non illo ratione tenetur eveniet. Animi placeat iure amet."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492783407437",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-08-15T08:12:43",
            "utc": "2023-08-15T12:12:43Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-09-09T06:01:38",
            "utc": "2023-09-09T10:01:38Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:41:59Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Non illo ratione tenetur eveniet. Animi placeat iure amet.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492783407437",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492783407437/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Eius quasi sunt architecto. Soluta inventore iusto.",
            "html": "Eius quasi sunt architecto. Soluta inventore iusto."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492765062567",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-08-29T17:30:35",
            "utc": "2023-08-29T21:30:35Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-10-07T01:35:46",
            "utc": "2023-10-07T05:35:46Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:28:27Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Eius quasi sunt architecto. Soluta inventore iusto.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492765062567",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492765062567/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Dolor inventore culpa fugit. Cupiditate at quidem fugiat labore recusandae dicta facere unde enim.",
            "html": "Dolor inventore culpa fugit. Cupiditate at quidem fugiat labore recusandae dicta facere unde enim."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492781190807",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-09-10T04:42:17",
            "utc": "2023-09-10T08:42:17Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-08-10T04:07:55",
            "utc": "2024-08-10T08:07:55Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:52Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Dolor inventore culpa fugit. Cupiditate at quidem fugiat labore recusandae dicta facere unde enim.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492781190807",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492781190807/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Exercitationem voluptatibus inventore soluta quis assumenda nihil impedit aliquid. Nisi voluptatibus amet repellat corrupti quae.",
            "html": "Exercitationem voluptatibus inventore soluta quis assumenda nihil impedit aliquid. Nisi voluptatibus amet repellat corrupti quae."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492783387377",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-09-23T19:23:14",
            "utc": "2023-09-23T23:23:14Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-06-27T07:10:18",
            "utc": "2024-06-27T11:10:18Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:41:58Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Exercitationem voluptatibus inventore soluta quis assumenda nihil impedit aliquid. Nisi voluptatibus amet repellat corrupti quae.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492783387377",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492783387377/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Natus voluptatem ex beatae neque ad modi voluptatibus. Velit illo itaque ea atque.",
            "html": "Natus voluptatem ex beatae neque ad modi voluptatibus. Velit illo itaque ea atque."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492779004267",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-09-30T14:56:33",
            "utc": "2023-09-30T18:56:33Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-12-17T16:14:26",
            "utc": "2023-12-17T21:14:26Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:05Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Natus voluptatem ex beatae neque ad modi voluptatibus. Velit illo itaque ea atque.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492779004267",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492779004267/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Tempore modi totam facere exercitationem aliquid enim possimus. Laborum pariatur vero aperiam quas tenetur.",
            "html": "Tempore modi totam facere exercitationem aliquid enim possimus. Laborum pariatur vero aperiam quas tenetur."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492778984207",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-10-23T21:29:14",
            "utc": "2023-10-24T01:29:14Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-02-21T06:16:52",
            "utc": "2024-02-21T11:16:52Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:02Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Tempore modi totam facere exercitationem aliquid enim possimus. Laborum pariatur vero aperiam quas tenetur.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492778984207",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492778984207/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Molestias odit voluptatem nulla error saepe quia illo. Eligendi ex ab.",
            "html": "Molestias odit voluptatem nulla error saepe quia illo. Eligendi ex ab."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492782304137",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-10-26T21:43:31",
            "utc": "2023-10-27T01:43:31Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2023-12-06T23:06:13",
            "utc": "2023-12-07T04:06:13Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:40:19Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Molestias odit voluptatem nulla error saepe quia illo. Eligendi ex ab.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492782304137",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492782304137/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Officia ad blanditiis maiores voluptatibus. Fugit porro commodi quos explicabo nihil sapiente possimus dicta vel.",
            "html": "Officia ad blanditiis maiores voluptatibus. Fugit porro commodi quos explicabo nihil sapiente possimus dicta vel."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492781110567",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-11-01T18:42:34",
            "utc": "2023-11-01T22:42:34Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-05-13T20:05:21",
            "utc": "2024-05-14T00:05:21Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:38:48Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Officia ad blanditiis maiores voluptatibus. Fugit porro commodi quos explicabo nihil sapiente possimus dicta vel.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492781110567",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492781110567/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Unde incidunt incidunt voluptates quis. Dolorum exercitationem modi at sint culpa a sunt alias enim.",
            "html": "Unde incidunt incidunt voluptates quis. Dolorum exercitationem modi at sint culpa a sunt alias enim."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492778944087",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-11-20T19:19:48",
            "utc": "2023-11-21T00:19:48Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-02-12T09:57:31",
            "utc": "2024-02-12T14:57:31Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:37:49Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Unde incidunt incidunt voluptates quis. Dolorum exercitationem modi at sint culpa a sunt alias enim.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492778944087",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492778944087/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    },
    {
        "name": {
            "text": "Summer Music Fest",
            "html": "Summer Music Fest"
        },
        "description": {
            "text": "Rem quaerat explicabo. Nam itaque quo repellendus.",
            "html": "Rem quaerat explicabo. Nam itaque quo repellendus."
        },
        "url": "https://www.eventbrite.com/e/summer-music-fest-tickets-492783577947",
        "start": {
            "timezone": "America/New_York",
            "local": "2023-12-02T20:51:50",
            "utc": "2023-12-03T01:51:50Z"
        },
        "end": {
            "timezone": "America/New_York",
            "local": "2024-06-05T16:59:54",
            "utc": "2024-06-05T20:59:54Z"
        },
        "organization_id": "1322280652203",
        "created": "2022-12-20T17:42:14Z",
        "changed": "2022-12-21T21:47:38Z",
        "capacity": 0,
        "capacity_is_custom": false,
        "status": "draft",
        "currency": "USD",
        "listed": true,
        "shareable": false,
        "invite_only": false,
        "online_event": false,
        "show_remaining": false,
        "tx_time_limit": 1200,
        "hide_start_date": false,
        "hide_end_date": false,
        "locale": "en_US",
        "is_locked": false,
        "privacy_setting": "unlocked",
        "is_series": false,
        "is_series_parent": false,
        "inventory_type": "limited",
        "is_reserved_seating": false,
        "show_pick_a_seat": false,
        "show_seatmap_thumbnail": false,
        "show_colors_in_seatmap_thumbnail": false,
        "source": "api",
        "is_free": true,
        "version": null,
        "summary": "Rem quaerat explicabo. Nam itaque quo repellendus.",
        "facebook_event_id": null,
        "logo_id": null,
        "organizer_id": "58508632433",
        "venue_id": null,
        "category_id": null,
        "subcategory_id": null,
        "format_id": null,
        "id": "492783577947",
        "resource_uri": "https://www.eventbriteapi.com/v3/events/492783577947/",
        "is_externally_ticketed": false,
        "logo": null,
        "ticket_classes": []
    }
]
